export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';
export const UPDATE_CART_OBJECT = 'UPDATE_CART_OBJECT';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const RESTORE_CART_OBJECT = 'RESTORE_CART_OBJECT';